### PR TITLE
Remove manual adding cachyos repository

### PR DESCRIPTION
**Pull request by SoongVilda**
I believe this is better because users could edit `/etc/pacman.conf` incorrectly and end up with a broken system. Manual adding is also useless because we already have a script.

README.md is already pretty long and I want to reduce the amount of information and make our README.md more effective.

### CODE REVIEW

**Comment by ptr1337** [comment]
Personally Im against this. This information is quite important for people which would "not" trust our scripts or anything else and want to handle things manually.

**Comment by ventureoo** [comment]
> Personally Im against this. This information is quite important for people which would "not" trust our scripts or anything else and want to handle things manually.

well, I think people if they don't trust us, then they may not trust the binary packages and build themselves...

**Comment by ventureoo** [comment]
I think we should also change the commands to use get script from wget to git + chmod, for people who are paranoid

**Comment by SoongVilda** [comment]
Okay, then you can close the PR and I'll just send another PR only with some sentence fixes.

**Pull request closed without merging**
