### PR TITLE
Clarify description of the full tickless value

### PR DESCRIPTION
**Pull request by ventureoo**
See https://github.com/Frogging-Family/linux-tkg/pull/636 for more info.

### CODE REVIEW

**Review by sirlucjan — APPROVED** [review]

**Comment by sirlucjan** [comment]
Could you update all PKGBUILDS?

**Comment by ptr1337** [comment]
That is not correct.
In 6.1 (or 6.2 not sure) where RCU_NOCB_DEFAULT_ALL introduced, which does automatically offload CPUs.
The kernel parameter is not required then. We have this option as default since 6.1 enabled.

if nohzfull kernel parameter is set, then it will respect that.

**Comment by ventureoo** [comment]
> That is not correct. In 6.1 (or 6.2 not sure) where RCU_NOCB_DEFAULT_ALL introduced, which does automatically offload CPUs. The kernel parameter is not required then. We have this option as default since 6.1 enabled.
> 
> if nohzfull kernel parameter is set, then it will respect that.

Please read my explanation in PR for TKG. Even if the parameter is not required, it still doesn't work properly, since nohz_full implies that we don't make ticks when we have one task running per-CPU core. This is not possible in desktop tasks when too many processes are fighting for CPU time.

**Comment by ventureoo** [comment]
> Could you update all PKGBUILDS?

I added the missing one for linux-cachyos-server.

**Comment by ptr1337** [comment]
> > That is not correct. In 6.1 (or 6.2 not sure) where RCU_NOCB_DEFAULT_ALL introduced, which does automatically offload CPUs. The kernel parameter is not required then. We have this option as default since 6.1 enabled.
> > if nohzfull kernel parameter is set, then it will respect that.
> 
> Please read my explanation in PR for TKG. Even if the parameter is not required, it still doesn't work properly, since nohz_full implies that we don't make ticks when we have one task running per-CPU core. This is not possible in desktop tasks when too many processes are fighting for CPU time. This is the reason why this parameter is usually paired with isolcpus.

https://lore.kernel.org/lkml/20220422175247.2197949-1-joel@joelfernandes.org/T/

```
On systems with CONFIG_RCU_NOCB_CPU=y, there is no default mask provided
which ends up not offloading any CPU. This patch removes a dependency
from the bootloader having to know about RCU and about how to provide
the mask.

With the new option enabled, all CPUs will be offloaded on boot unless
rcu_nocbs= or rcu_nohz_full= kernel parameters provide a CPU list.
```

**Comment by ventureoo** [comment]
I don't understand how a change in the RCU should generally affect the behavior of the full tickless timer. Anyway, closing.

**Pull request closed without merging**
