### PR TITLE
Revert "cachyos: add new cpu flags" for LTS kernel.

### PR DESCRIPTION
**Pull request by andersrh**
This commit reverts a part of commit 593a4ec8685b7964d9a91683b1dc410386790c53

LTS is still using an old patch and therefore doesn't support the new params for setting CPU optimization.

### CODE REVIEW

**Comment by 1Naim** [comment]
Can you revert the changes in the config too?

**Comment by andersrh** [comment]
> Can you revert the changes in the config too?

yes. done :-)

**Comment by sirlucjan** [comment]
Could you restore these values? https://github.com/CachyOS/linux-cachyos/pull/301/commits/a95eff69b2c36f54063ca58a97925b3450edf74e#diff-b9c0cfc425df392e268a51699b308b6290f4a4a96f680fcd7af1cf8ff1671490

**Comment by 1Naim** [comment]
> Could you restore these values? [a95eff6#diff-b9c0cfc425df392e268a51699b308b6290f4a4a96f680fcd7af1cf8ff1671490](https://github.com/CachyOS/linux-cachyos/commit/a95eff69b2c36f54063ca58a97925b3450edf74e#diff-b9c0cfc425df392e268a51699b308b6290f4a4a96f680fcd7af1cf8ff1671490)

It's already restored as part of the weekly sync.

**Review by 1Naim — APPROVED** [review]
LGTM

**Comment by ptr1337** [comment]
Fixed with:

https://github.com/CachyOS/kernel-patches/commit/46495212d84fcd30ca5906f37b1e08035d2256f6

**Pull request closed without merging**
