### PR TITLE
Use modprobed-db for CI builds to fix the lack of space

### PR DESCRIPTION
**Pull request by ventureoo**
Unfortunately, I can't find any other way other than to disable “fat” modules like i915/nouveau/amdgpu/network drivers. We don't patch them much though.

### CODE REVIEW

**Comment by ptr1337** [comment]
Why not just putting a modprobe.d-db entry in?

**Comment by ventureoo** [comment]
> Why not just putting a modprobe.d-db entry in?

If you already have a prepared module list, then I don't mind.

**Comment by ptr1337** [comment]
> > Why not just putting a modprobe.d-db entry in?
> 
> If you already have a prepared module list, then I don't mind.

https://paste.cachyos.org/p/bbdbe24.txt

Here is mine. We could merge from some other computers too and then use that one

**Review by ptr1337 — APPROVED** [review]
LGTM, thank you.

**Pull request merged**
