### PR TITLE
Fix LTO&kCFI

### PR DESCRIPTION
**Pull request by aarrayy**
This fixes clang from complaining about unsupported flags.

### CODE REVIEW

**Review by ptr1337 — APPROVED** [review]
LGTM

**Comment by ventureoo** [comment]
linux-cachyos-server was missed there

**Comment by aarrayy** [comment]
I did not include it because it wasn't there even before the fix so i thought i was not meant for the server kernel

**Comment by ptr1337** [comment]
Will be removed anyways, since it gets handled over the Kernels Makefile. Will be in 6.7.2 included.

**Pull request merged**
